theme: "hugo-PaperMod"
baseURL: https://social-paths.github.io/
# languageCode: en-us
title: Social Paths
outputs:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Social Paths"
    home:
        - HTML
        - RSS
        - JSON # is necessary

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                # - name: Arquivo
                #   url: archives/
                #   weight: 5
                - name: Busca
                  pre: "a"
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categorias
                  url: categories/
                  weight: 10
                - name: Sobre 
                  url: about/
                  weight: 20
                  

params:

    homeInfoParams:
        Title: "Olá \U0001F44B"
        Content: >
            - Bem vindo ao [repositório](https://github.com/social-paths/social-paths.github.io) de conteúdos relacionados à pesquisa em Economia e Ciências
            Socials Aplicadas. Este repositório visa reunir recursos e ferramentas que 
            auxiliam o pesquisador e pesquisadora na condução de um trabalho empírico. Os tópicos 
            de interesse são:
            
            - • **Programação** (R, stata, python, git, linux shell, etc)

            - • Base de **Dados** (onde encontrar e como trabalhar com eles) 
            
            - • Resultados recentes em econometria (aplicada), inferência causal etc. 
          
    socialIcons: # optional
        - name: "github"
          url: "https://github.com/organizations/social-paths/"

    fuseOpts: # search options
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    # optional options
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    
    

markup:
  goldmark:
    renderer:
      unsafe: true # for some stuff! necessary!
